backend:
  name: github
  repo: sohaibymani-boop/site-alsiraj   # <--- تأكد من كتابة اسمك الصحيح
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "services"
    label: "الخدمات"
    folder: "_data/services"
    create: true
    fields:
      - { label: "اسم الخدمة", name: "title", widget: "string" }
      - { label: "الوصف", name: "description", widget: "text" }
      - { label: "عدد النجوم", name: "stars", widget: "number", min: 1, max: 5, default: 5 }
      - { label: "صورة الخدمة", name: "image", widget: "image" }

  - name: "testimonials"
    label: "آراء العملاء"
    folder: "_data/testimonials"
    create: true
    fields:
      - { label: "اسم العميل", name: "client_name", widget: "string" }
      - { label: "الرأي", name: "content", widget: "text" }
      - { label: "التقييم", name: "rating", widget: "number", min: 1, max: 5 }

  - name: "gallery"
    label: "معرض الصور"
    folder: "_data/gallery"
    create: true
    fields:
      - { label: "عنوان الصورة", name: "title", widget: "string" }
      - { label: "الصورة", name: "image", widget: "image" }